FROM wordpress:php7.3-apache

# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Install Less for WP-CLI
RUN apt-get update && apt-get -y install less

# Install mysql client (for the wp core install)
RUN apt-get -y install default-mysql-client

# Install WP-CLI
RUN cd ~ && curl -k -L \
    https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp && chmod +x /usr/local/bin/wp